### ISSUE TITLE
采用更缓和的 .NET 版本跟进策略，或保持一定兼容性

### ISSUE THREAD

**Issue by Wenti-D** [KyouyamaKazusa0805/Sudoku#741]
.NET 9 五天前刚刚发布，据我观察，此项目早早就切换到了 .NET 9，而用户方面不一定会跟进得如此之快，不建议早早就切换到 .NET 9。（后续的新版 .NET 也一样。）或者也可以考虑附加发布仍然兼容上一个 .NET 正式版的程序，带来一个缓冲期。

~~（如果真有什么非用不可的最新版特性那当我没说。）~~

**Comment by KyouyamaKazusa0805** [comment]
两个原因：

第一是，这项目最开始就是为了试用新特性才这么做的。就指着它练手呢。

第二是，我这人非常不擅长兼容老版本，大多数特性改名改文件，你观察这么长时间肯定会注意到这种问题；那你也思考思考为啥我会这么干？我难道不想兼容么，那不就因为我不擅长所以我才迫不得已么。代码越写越复杂，试了新写法后发现老写法就没那个必要了，当然就删代码重构了。学习是有个过程的，又不是一上来我就能掌握全部的东西。

至于缓冲期啥的，我倒是更建议你自己拿去编译打包成其他版本。代码都是上传了的，你自己弄弄就行了。
